services:
  db:
    image: mysql:9.2.0
    environment:
      MYSQL_DATABASE: 'dicom_db'
      MYSQL_USER: 'dicom_user'
      MYSQL_PASSWORD: 'dicom_password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Mounts the named volume

volumes:
  db_data: